let quotes = [
    "Why are you trying so hard to fit in, when you were born to stand out? - Ian Wallace",
    "Happiness can be found, even in the darkest of times, if one only remembers to turn on the light. - Albus Dumbledore",
    "Life moves pretty fast. If you don’t stop and look around once in a while, you could miss it. - Ferris Bueller",
    "At some point, you just pull off the Band-Aid, and it hurts but then it’s over and you’re relieved. - John Green",
    "You is kind. You is smart. You is important. - Aibileen Clark",
    "The past can hurt. But the way I see it, you can either run from it or learn from it. - Rafiki",
    "We accept the love we think we deserve. - Stephen Chbosky",
    "Why do we fall? So we can learn to pick ourselves back up. - Thomas Wayne",
    "Don’t lose track of who you are just because it might be easier to be somebody else. - Will Schuster",
    "You can’t change your past. But you can let go and start your future. - Quinn Fabray",
    "Numbing the pain for a while will make it worse when you finally feel it. - Albus Dumbledore",
    "Do or do not. There is no try. - Yoda",
    "You can’t live your life for other people. You’ve got to do what’s right for you, even if it hurts some people you love. - Nicholas Sparks",
    "Don’t let anyone ever make you feel like you don’t deserve what you want. - Patrick Verona",
    "All we have to decide is what to do with the time that is given us. - J.R.R. Tolkien",
    "To live is the rarest thing in the world. Most people just exist, that is all. - Oscar Wilde",
    "Say everything you’ve always wanted, be not afraid of who you really are. - A Great Big World",
    "It isn’t where you came from; it’s where you’re going that counts. - Ella Fitzgerald",
    "If we’re strong enough to let it in, we’re strong enough to let it go. - Birdy & Rhodes",
    "Seek to be worth knowing rather than be well known. - Unknown",
    "Comparison is the thief of joy. - Theodore Roosevelt",
    "Major or minor, if something keeps you human when pressure makes you feel like a volcano, hold on to that thing by whatever means necessary. - Talia Hibbert",
    "The risk of being authentic is being disliked. The result of being liked by everyone is never becoming anyone. - Officially Divinity",
    "And if we let happy things make us unhappy when they stopped, there would be no point having happy things. - Alexis Hall",
    "It turns out life isn’t a puzzle that can be solved one time and it’s done. You wake up every day, and you solve it again. - Chidi Anagonye",
    "The night is darkest just before the dawn. - Harvey Dent",
    "If you can’t love yourself, how in the hell you gonna love somebody else? - Rupaul",
    "It always seems impossible until it’s done. - Nelson Mandela",
    "When you were born, you cried and the world rejoiced. Live your life so that when you die, the world cries and you rejoice. - Cherokee Proverb",
    "Every storm runs out of rain. - Maya Angelou",
    "Fate whispers to the warrior, “You cannot withstand the storm.” The warrior whispered back, “I am the storm.” - Jake Remington",
    "You can do anything, but you can’t do everything. - David Allen",
    "You are immortal; you’ve existed for billions of years in different manifestations, because you are Life, and Life cannot die. You are the trees, the butterflies, the fish, the air, the moon, the sun. Wherever you go, you are there, waiting for yourself. - Don Miguel Ruiz",
    "The meaning of life is just to be alive. It is so plain and so obvious and so simple. And yet, everybody rushes around in a great panic as if it were necessary to achieve something beyond themselves. - Alan W. Watts",
    "What if I fall? Oh but darling, what if you fly? - Erin Hanson",
    "A dream can be a distraction just as well as it can be a goal. - Mr. Johnson",
    "Enjoy the little things in life because one day you will look back and realize they were the big things. - Kurt Vonnegut Jr.",
    "Just a bad day, not a bad life. - Bring Me the Horizon & Sigrid",
    "What if you had nothing to prove? Imagine what you could create. - Dr. Dana Varga",
    "You can be the ripest, juiciest peach in the world, and there's still going to be somebody who hates peaches. - Dita Von Teese",
    "The best time to plant a tree is 20 years ago. The second best time is now. - Maurice Kremer",
    "Some of your hurts you have cured, and the sharpest you’ve even survived. But what torments of grief you’ve endured from evils which never arrived. - Ralph Waldo Emerson",
    "Enjoy yourself, it’s later than you think. - Guy Lombardo",
    "Every knot was once straight rope. - Stephen Sondheim",
    "Awake. Love. Think. Speak. Be walking trees. Be talking beasts. Be divine waters. - C.S. Lewis",
    "Let go of who you think you’re supposed to be; embrace who you are. - Brené Brown",
    "You either walk inside your story and own it or you stand outside your story and hustle for your worthiness. - Brené Brown",
    "We don’t have to do it all alone. We were never meant to. - Brené Brown",
    "If I am not good to myself, how can I expect anyone else to be good to me? - Maya Angelou",
    "Courage is not the absence of fear, but rather the judgement that something else is more important than fear. - Ambrose Redmoon",
    "You cannot win the war against the world, if you can’t win the war against your own mind. - Will Smith",
    "Don’t you quit. You do make a difference. You do make a difference. You do make a difference. As weak as you are, as tired as you are, as many mistakes as you’ve made, you do make a difference. There is something they would lose if you were not there. - TD Jakes",
    "People’s opinion of you is none of your business, nor should you make it yours. - Steve Harvey",
    "You can’t let your failures define you, you have to let your failures teach you. - Barack Obama",
    "Insecurity kills more dreams than failure ever will. - Suzy Kassem",
    "If you focus on what you’ve left behind you will never be able to see what lies ahead. - Chef Gusteau",
    "Worrying is like a rocking chair, it gives you something to do but it doesn’t get you anywhere. - Glenn Turner",
    "You don’t have to control your thoughts. You just have to stop letting them control you. - Dan Millman",
    "Growth is growth, no matter how small. - Brian Tracy",
    "We’ve all got both light and dark inside us. What matters is the part we choose to act on… that’s who we really are. - Sirius Black",
    "If you want something you’ve never had, you must do something you’ve never done. - Thomas Jefferson",
    "A bad day is still a luxury. - Libby Christensen"
]

function newQuote() {
    let randomNum = Math.floor(Math.random() * (quotes.length));
    document.getElementById('quoteDisplay').innerHTML = quotes[randomNum];
}

let affirms = [
    "I am the one thing in life I can control. I am inimitable, I am an original.",
    "I don’t chase, I attract. What belongs to me will simply find me.",
    "I am in charge of my thoughts and feelings.",
    "I believe in myself and am consistent.",
    "All the experiences of my life make it unique.",
    "I am enough.",
    "I am aligning myself with freedom, growth, and joy.",
    "I release any fears holding me back from being the best version of myself.",
    "It is safe for me to let go of my past.",
    "What I say and do matters.",
    "I trust the timing of my life.",
    "I am no longer going to struggle because I no longer need to prove myself.",
    "I am worthy and enough, just as I am.",
    "I trust my body and its wisdom.",
    "I am rooted in the present moment.",
    "I am exactly where I’m meant to be.",
    "I am open to life’s experiences.",
    "I am stronger than I know."
]

function newAffirm() {
    let randomNum = Math.floor(Math.random() * (affirms.length));
    document.getElementById('affirmDisplay').innerHTML = affirms[randomNum];
}